### ISSUE TITLE
Grouped annotations: order

### ISSUE THREAD

**Issue by valeriavitale** [machines-reading-maps/mrm-recogito-ui#25]
Make the information about grouped annotation and their order visible in the download

**Comment by rsimon** [comment]
I'm renaming this to 'Grouped annotations: order' because that's a new feature. The part about CSV export is already covered here: #14

**Comment by rsimon** [comment]
A first (but incomplete!) version is now deployed to the server. Punch-list of items still to be addressed:

- [ ] When opening an un-ordered group, and enabling ordering, the sequence number of the selected annotation isn't 
  updated in the widget
- [ ] Changing the ordering isn't possible in the UI yet
- [ ] Removing an annotation from an ordered group doesn't remove the label
- [ ] Removing an annotation from an ordered group doesn't re-adjust the sequence numbers of the remaining annotations
- [ ] Ordering labels aren't compatible with Gigapixel Mode yet (used for WMTS)
