### ISSUE TITLE
Controlled vocabulary as option in annotation preferences

### ISSUE THREAD

**Issue by valeriavitale** [machines-reading-maps/mrm-recogito-ui#26]
The current tag suggestions interfere with the document-specific list that users may want to upload. An option in annotation preferences should allow users to choose, for each document, between general suggestions and tailored lists

**Comment by rsimon** [comment]
After our meeting, I wondered whether there even is a use case for mixing tag systems (i.e. have both the uploaded tags __and__  the smart suggestions). If not, a much quicker fix would be to disable the smart suggestions as soon as a custom vocabulary is set.

**Comment by valeriavitale** [comment]
I think that would work. If someone uploads a list, I assume they don't really want to see other suggestions.

**Comment by rsimon** [comment]
Ok, I'll implement it like this for now - we can always add an extra setting in the "Annotation Preferences" later.

**Comment by rsimon** [comment]
The quick solution (API suggestions automatically off, as soon as the document has a custom vocab configured) is now implemented!
